#' read a ScanR data table
#'
#' Use \code{data.table::fread} to (quickly) load a parameter data file
#' generated by ScanR and run the usual operations that make it usable.
#'
#' This is a simple wrapper for fread from the package data.table.
#' It also uses some dplyr functions to modify the resulting data.table.
#' Some columns will be discarded. Usually the variables that are to be kept
#' will contain a specific pattern, e.g. an underscore (\code{_}).
#'
#' The \code{data.table} class is stripped from the object.
#'
#' @param path path to file
#' @param pattern regular expression to select variables to keep
#'
#' @return a data frame
#'
#' @importFrom magrittr %>%
#'
#' @export

freader <- function(path, pattern = '_') {
  data.table::fread(path, check.names = TRUE) %>%
    dplyr::filter(nuclei == 1) %>%
    dplyr::rename(well = Parent.Object.ID..Well.) %>%
    dplyr::mutate(well = well + 1) %>%
    dplyr::select(well, dplyr::matches(pattern)) %>%
    data.frame(stringsAsFactors = FALSE)
}
